.PHONY: evidence scrub

## evidence — capture a point-in-time evidence pack under out/evidence/
evidence:
	mkdir -p out/evidence
	./scripts/capture_evidence.sh
	shasum -a 256 out/evidence/*.txt > out/evidence/checksums.sha256
	@echo ""
	@echo "Checksums written to out/evidence/checksums.sha256"

## scrub — scan repo for suspicious filenames and content (pre-push check)
scrub:
	@echo "=== Filename scan ==="
	@found=$$(find . -type f \
	  | grep -v '\.git/' | grep -v 'out/' | grep -v '.venv/' \
	  | grep -iE 'claude|anthropic|prompt|context|llm|agent|scratch|notes|todo_ai|instructions|memory|journal' \
	  || true); \
	if [ -z "$$found" ]; then echo "OK — no suspicious filenames"; \
	else echo "FAIL:"; echo "$$found"; exit 1; fi
	@echo ""
	@echo "=== Content scan ==="
	@found=$$(grep -rn \
	  --include='*.py' --include='*.sh' --include='*.md' \
	  --include='*.sql' --include='*.yml' --include='*.yaml' \
	  --include='*.txt' --include='*.json' \
	  --include='Dockerfile' --include='.env.example' \
	  -iE 'claude|anthropic|\bllm\b|prompt|context pack|\bagent\b|as an ai|generated by' \
	  --exclude-dir='.git' --exclude-dir='.claude' \
	  --exclude-dir='.venv' --exclude-dir='out' \
	  --exclude='Makefile' --exclude='capture_evidence.sh' \
	  . || true); \
	if [ -z "$$found" ]; then echo "OK — no suspicious content"; \
	else echo "FAIL:"; echo "$$found"; exit 1; fi
